### ISSUE TITLE
How to debug tu binary

### ISSUE THREAD

**Issue by PikachuHy** [tu-lang/tu#2]
Exciting project! 

I just built a simple hello.tu.
```
use fmt
func main() {
  fmt.println("Hello World")
}
```
then run `tu build hello.tu`
I got the `a.out` file

My question is how to debug the `a.out`.
more specifically,
- how to add a breakpoint
- how to watch local variable
- etc

Thanks.

**Comment by brewlin** [comment]
self debugging is currently not implemented, but it can be debugged through gcc compilation 
for example:
```
$ tu -s hello.tu -gcc -std -g
$ gcc *.s /usr/local/lib/coasm/*.s -nostdlib -e main
$ cgdb a.out
> b main
> r
> c
```
by the way, self debugging is currently developing

**Comment by brewlin** [comment]
self debugging is currently not implemented, but it can be debugged through gcc compilation
for example:
```
$ tu -s hello.tu -gcc -std -g
$ gcc *.s /usr/local/lib/coasm/*.s -nostdlib -e main
$ cgdb a.out
> b main_main
> r
> c
```
by the way, self debugging is currently developing
