### ISSUE TITLE
怎么方便接入其他语言的生态

### ISSUE THREAD

**Issue by dwdcth** [tu-lang/tu#3]
作者想法非常好，我也是想要动态语言+静态语言的组合。之前是看到dart，不过还是有虚拟机。
作者有没有考虑怎么和已有生态结合，重新造轮子代价太大。另外凸语言有没有一个切入点，打造一个杀手级应用。

**Comment by dwdcth** [comment]
是否可以从shell编程搞起，很方便的和系统命令集成，代替bash等。可以作为解释语言之间运行，也能编译成二进制运行

**Comment by brewlin** [comment]
目前的话 也是实现了c的abi，编译出来的库 ，可以支持c语言寄存器参数传参调用。不特别定义的话默认是栈传递参数
除了c的话和其他语言结合倒是没想过

关于开发一个实际应用的话还有点早，现在只完成了第一个阶段，下面要开始优化，和补充更多有意义的特性：如`rust的栈式协程，还有标准库增加net相关的库`
